name: "Daniel O'Rielly"
favicon: null
layout_spectrum: 0.8910453589633107
typography_spectrum: 0.5815017987042665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff8c17'
    - '#ff7610'
    - '#ffffff'
    - '#ffe5cc'
    - '#ffac64'
  brandStrength: 0.8125
  lightness: 0.5452587946783751
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
