name: "Daniel O'Rielly"
favicon: null
layout_spectrum: 0.8910453589633107
typography_spectrum: 0.5815017987042665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f99e33'
    - '#5f6062'
    - '#b3d88c'
    - '#000000'
    - '#ff0000'
  brandStrength: 0.8125
  lightness: 0.5452587946783751
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
